name: Telegram Notifier Pro+

on:
  push:
    branches: ['**']
    tags: ['**']
    paths-ignore: 
      - 'docs/**'
      - 'README.md'
  pull_request:
    types: [opened, closed, reopened, ready_for_review, synchronize]
  issues:
    types: [opened, closed, reopened, labeled, assigned]
  workflow_run:
    workflows: ["CI", "Tests", "Security Scan"]
    types: [completed, requested]
  release:
    types: [published, edited]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Send Smart Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ENVIRONMENT: ${{ github.event_name == 'release' && 'PROD' || 'DEV' }}
        run: |
          #!/bin/bash
          set -e

          # Configuración básica
          REPO_NAME="${{ github.repository }}"
          REPO_URL="${{ github.server_url }}/$REPO_NAME"
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")

          # Función para escapar caracteres especiales de MarkdownV2
          escape_markdown() {
            echo "$1" | sed -e 's/[_\*\[\]()~`\>#+\-=\|{}\.!]/\\&/g'
          }

          # Mensaje base
          MESSAGE=""

          # Detectamos evento y generamos mensaje
          case "${{ github.event_name }}" in

            "push")
              COMMIT_MSG=$(escape_markdown "${{ github.event.head_commit.message }}" | cut -c1-100)

              NUM_ADDED=$(echo "${{ github.event.head_commit.added }}" | wc -w 2>/dev/null || echo 0)
              NUM_MODIFIED=$(echo "${{ github.event.head_commit.modified }}" | wc -w 2>/dev/null || echo 0)
              NUM_CHANGES=$((NUM_ADDED + NUM_MODIFIED))

              if [ "$NUM_CHANGES" -gt 20 ]; then
                CHANGE_EMOJI="📦"
              elif [ "$NUM_CHANGES" -gt 5 ]; then
                CHANGE_EMOJI="📂"
              else
                CHANGE_EMOJI="📄"
              fi

              MESSAGE="🚀 *Push en $(escape_markdown "$REPO_NAME")* [$REPO_URL] ($REPO_URL) [$ENVIRONMENT]
                      \n▫️ *Rama*: \`$(escape_markdown "${GITHUB_REF##*/}")\`
                      \n▫️ *Autor*: [@$(escape_markdown "${{ github.actor }}")]($REPO_URL/${{ github.actor }})
                      \n▫️ *Commit*: [\`$SHORT_SHA\`](${{ github.event.head_commit.url }})
                      \n▫️ *Mensaje*: $COMMIT_MSG
                      \n${CHANGE_EMOJI} *Archivos modificados*: $NUM_CHANGES
                      \n🕒 *Hora*: $CURRENT_TIME"
              ;;

            "pull_request")
              PR_ACTION="${{ github.event.action }}"
              IS_MERGED="${{ github.event.pull_request.merged }}"
              case "$PR_ACTION" in
                "opened") EMOJI="🆕"; ACTION_TEXT="ABIERTO";;
                "closed") 
                  if [[ "$IS_MERGED" == "true" ]]; then
                    EMOJI="✅ MERGED"; ACTION_TEXT="CERRADO Y FUSIONADO";
                  else
                    EMOJI="❌ CLOSED"; ACTION_TEXT="CERRADO";
                  fi;;
                "reopened") EMOJI="🔁"; ACTION_TEXT="REABIERTO";;
                "ready_for_review") EMOJI="👀"; ACTION_TEXT="LISTO PARA REVISIÓN";;
                "synchronize") EMOJI="🔄"; ACTION_TEXT="ACTUALIZADO";;
                *) EMOJI="🔀"; ACTION_TEXT="ACCION DESCONOCIDA";;
              esac

              PR_TITLE=$(escape_markdown "${{ github.event.pull_request.title }}")
              HEAD_BRANCH=$(escape_markdown "${{ github.event.pull_request.head.ref }}")
              BASE_BRANCH=$(escape_markdown "${{ github.event.pull_request.base.ref }}")
              PR_AUTHOR=$(escape_markdown "${{ github.event.pull_request.user.login }}")
              PR_URL="${{ github.event.pull_request.html_url }}"

              MESSAGE="$EMOJI *PR $ACTION_TEXT: [$PR_TITLE]($PR_URL)*
                      \n▫️ *Por*: [@$PR_AUTHOR]($REPO_URL/$PR_AUTHOR)
                      \n▫️ *Rama*: \`$HEAD_BRANCH → $BASE_BRANCH\`
                      \n▫️ *Estado*: ${{ github.event.pull_request.state }}
                      \n📊 *Cambios*: +{{ github.event.pull_request.additions }} -{{ github.event.pull_request.deletions }} (\`${{ github.event.pull_request.changed_files }} archivos\`)
                      \n🕒 *Actualizado*: $CURRENT_TIME"
              ;;

            "issues")
              ISSUE_ACTION="${{ github.event.action }}"
              ISSUE_ACTION_UPPER=$(echo "$ISSUE_ACTION" | awk '{print toupper($0)}')

              ISSUE_TITLE=$(escape_markdown "${{ github.event.issue.title }}")
              ISSUE_URL="${{ github.event.issue.html_url }}"
              ISSUE_AUTHOR=$(escape_markdown "${{ github.event.issue.user.login }}")
              ASSIGNEE=$(escape_markdown "${{ github.event.issue.assignee.login }}")
              [ -z "$ASSIGNEE" ] && ASSIGNEE="sin asignar"

              ISSUE_LABELS=$(echo "${{ github.event.issue.labels.*.name }}" | tr ' ' '\n' | grep -v '^$' | tr '\n' ',' | sed 's/,$//')
              [ -z "$ISSUE_LABELS" ] && ISSUE_LABELS="ninguna"

              case "$ISSUE_ACTION" in
                "opened") ISSUE_EMOJI="⚠️";;
                "closed") ISSUE_EMOJI="✅";;
                "reopened") ISSUE_EMOJI="🔁";;
                "labeled") ISSUE_EMOJI="🏷️";;
                "assigned") ISSUE_EMOJI="👤";;
                *) ISSUE_EMOJI="ℹ️";;
              esac

              MESSAGE="$ISSUE_EMOJI *Issue $ISSUE_ACTION_UPPER: [$ISSUE_TITLE]($ISSUE_URL)*
                      \n▫️ *Por*: [@$ISSUE_AUTHOR]($REPO_URL/$ISSUE_AUTHOR)
                      \n▫️ *Asignado a*: [@$ASSIGNEE]($REPO_URL/$ASSIGNEE)
                      \n🏷️ *Etiquetas*: $(escape_markdown "$ISSUE_LABELS")
                      \n▫️ *Estado*: ${{ github.event.issue.state }} | 💬 ${{ github.event.issue.comments }} comentarios
                      \n🕒 *Actualizado*: $CURRENT_TIME"
              ;;

            "workflow_run")
              WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
              CREATED_AT="${{ github.event.workflow_run.created_at }}"
              UPDATED_AT="${{ github.event.workflow_run.updated_at }}"
              CREATED_TIMESTAMP=$(date -d "$CREATED_AT" +%s)
              UPDATED_TIMESTAMP=$(date -d "$UPDATED_AT" +%s)
              DURATION_SEC=$((UPDATED_TIMESTAMP - CREATED_TIMESTAMP))
              DURATION_STR=$(printf '%02d:%02d' $((DURATION_SEC/60)) $((DURATION_SEC%60)))

              CONCLUSION="${{ github.event.workflow_run.conclusion }}"
              case "$CONCLUSION" in
                "success") EMOJI="✔️"; STATUS="EXITOSO";;
                "failure") EMOJI="❌"; STATUS="FALLIDO";;
                "cancelled") EMOJI="🛑"; STATUS="CANCELADO";;
                "skipped") EMOJI="⏭️"; STATUS="OMITIDO";;
                *) EMOJI="ℹ️"; STATUS="$(escape_markdown "$CONCLUSION")";;
              esac

              MESSAGE="$EMOJI *Workflow [$WORKFLOW_NAME](${{ github.event.workflow_run.html_url }}) $STATUS*
                      \n▫️ *Duración*: $DURATION_STR
                      \n▫️ *Commit*: [\`$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)\`]($REPO_URL/commit/${{ github.event.workflow_run.head_sha }})
                      \n▫️ *Trigger*: ${{ github.event.workflow_run.event }} | *Ejecutado por*: $(escape_markdown "${{ github.event.workflow_run.actor.login }}")
                      \n🕒 *Finalizado*: $CURRENT_TIME"
              ;;
              
            "release")
              RELEASE_ACTION="${{ github.event.action }}"
              case "$RELEASE_ACTION" in
                "published") EMOJI="🎉";;
                "edited") EMOJI="✏️";;
                *) EMOJI="📌";;
              esac

              TAG_NAME=$(escape_markdown "${{ github.event.release.tag_name }}")
              RELEASE_NAME=$(escape_markdown "${{ github.event.release.name }}")
              RELEASE_BODY=$(echo "${{ github.event.release.body }}" | head -n 3 | sed 's/\n/ /g' | escape_markdown)
              HTML_URL="${{ github.event.release.html_url }}"

              MESSAGE="$EMOJI *Nuevo release [$TAG_NAME]($HTML_URL)*
                      \n📌 *Título*: $RELEASE_NAME
                      \n📝 *Descripción*: $RELEASE_BODY...
                      \n🏷️ *Pre-release*: ${{ github.event.release.prerelease }} | *Draft*: ${{ github.event.release.draft }}
                      \n🕒 *Publicado*: $CURRENT_TIME"
              ;;
          esac

          # Envío con manejo de errores
          echo "Sending notification to Telegram..."
          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot $TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="MarkdownV2" \
            -d disable_web_page_preview="true" \
            -w "\n%{http_code}")

          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)

          if [ "$HTTP_CODE" != "200" ]; then
            echo "::error::Failed to send Telegram notification. HTTP Code: $HTTP_CODE"
            echo "Response Body: $RESPONSE_BODY"
            exit 1
          else
            echo "✅ Notification sent successfully!"
          fi

        shell: bash