name: Telegram Notifier
on:
  push:
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, closed, reopened]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Formatea el mensaje según el evento
          case "${{ github.event_name }}" in
            "push")
              MESSAGE="📌 *Push en ${{ github.repository }}*
                      🌿 *Rama*: ${GITHUB_REF##*/}
                      👤 *Autor*: ${{ github.actor }}
                      📝 *Commit*: \`$(echo "${{ github.event.head_commit.message }}" | cut -c1-50)\`
                      🔗 [Ver cambios](${{ github.event.head_commit.url }})"
              ;;
            "pull_request")
              MESSAGE="🔀 *PR ${{ github.event.action }}*: ${{ github.event.pull_request.title }}
                      👤 *Por*: ${{ github.actor }}
                      🌿 *Rama*: ${{ github.event.pull_request.head.ref }}
                      🔗 [Ver PR](${{ github.event.pull_request.html_url }})"
              ;;
            "issues")
              MESSAGE="⚠️ *Issue ${{ github.event.action }}*: ${{ github.event.issue.title }}
                      👤 *Por*: ${{ github.actor }}
                      🔗 [Ver Issue](${{ github.event.issue.html_url }})"
              ;;
          esac

          # Envía el mensaje a Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"